### ISSUE TITLE
can't access package

### ISSUE THREAD

**Issue by pradeep11dx** [HappyMaki/MyFirstNakamas#1]
I can't access package. all are deleted. 
how can I use it ?

Thanks

**Comment by HappyMaki** [comment]
These packages are premium packages from the unity asset store. You need to purchase them to use them.

https://assetstore.unity.com/

Please see the readme. It lists the information out.

**Comment by pradeep11dx** [comment]
Hmm.. i think it was free in ur project 😁 i was looking for ultimate clean asset for free .... forget it 
thank u 😶
